package com.namazustudios.socialengine.model;

import javax.validation.constraints.NotNull;

/**
 * Represents a short link.  The short links are generated by the system and
 * can be tracked in some way.
 *
 * Created by patricktwohig on 6/9/15.
 */
public class ShortLink {

    private String id;

    private String shortLinkPath;

    private String shortLinkURL;

    @NotNull
    private String destinationURL;

    /**
     * Gets the path of the short link.  This is the path relative to
     * the short link url base.
     *
     * @return the short link path
     *
     */
    public String getShortLinkPath() {
        return shortLinkPath;
    }

    public void setShortLinkPath(String shortLinkPath) {
        this.shortLinkPath = shortLinkPath;
    }

    /**
     * Gets the ID of the link.
     *
     * @return the ID
     */
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the short link URL, this is the URL which can be shared
     * with the user.
     *
     * @return the short link URL
     */
    public String getShortLinkURL() {
        return shortLinkURL;
    }

    public void setShortLinkURL(String shortLinkURL) {
        this.shortLinkURL = shortLinkURL;
    }

    /**
     * Gets the destination, or target url.  This is the url to which
     * the short link URL redirects.
     *
     * @return the destination URL
     */
    public String getDestinationURL() {
        return destinationURL;
    }

    public void setDestinationURL(String destinationURL) {
        this.destinationURL = destinationURL;
    }

}
