package com.namazustudios.socialengine.model.session;

import com.namazustudios.socialengine.model.profile.Profile;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;
import java.util.Objects;

@ApiModel
public class SessionCreation {

    @ApiModelProperty("The Session Secret to pass to subsequent requests through headers.")
    private String sessionSecret;

    @ApiModelProperty("The Session object generated by the request.")
    private Session session;

    @ApiModelProperty("The session")
    private List<Profile> availableProfiles;

    public String getSessionSecret() {
        return sessionSecret;
    }

    public void setSessionSecret(String sessionSecret) {
        this.sessionSecret = sessionSecret;
    }

    public Session getSession() {
        return session;
    }

    public void setSession(Session session) {
        this.session = session;
    }

    public List<Profile> getAvailableProfiles() {
        return availableProfiles;
    }

    public void setAvailableProfiles(List<Profile> availableProfiles) {
        this.availableProfiles = availableProfiles;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SessionCreation)) return false;
        SessionCreation that = (SessionCreation) o;
        return Objects.equals(getSessionSecret(), that.getSessionSecret()) &&
                Objects.equals(getSession(), that.getSession()) &&
                Objects.equals(getAvailableProfiles(), that.getAvailableProfiles());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSessionSecret(), getSession(), getAvailableProfiles());
    }

}
