package com.namazustudios.socialengine.model.session;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel
public class SessionCreation {

    @ApiModelProperty("The Session Secret to pass to subsequent requests through headers.")
    private String sessionSecret;

    @ApiModelProperty("The Session object generated by the request.")
    private Session session;

    public String getSessionSecret() {
        return sessionSecret;
    }

    public void setSessionSecret(String sessionSecret) {
        this.sessionSecret = sessionSecret;
    }

    public Session getSession() {
        return session;
    }

    public void setSession(Session session) {
        this.session = session;
    }

}
