image:
  name: elementalcomputing/elements-web-services-ci:01993b3c8062b910c0bf1e8eb5ec7940457eaab2
  username: $DOCKER_HUB_USER
  password: $DOCKER_HUB_ACCESS_TOKEN

definitions:
  services:
    docker:
      image: docker:dind

clone:
  depth: full

pipelines:
  tags:
    "*":
      - step:
          size: 4x
          name: Build and Deploy Tags
          services:
            - docker
          runs-on:
            - "linux"
            - "self.hosted"
          script:
            - make setup_release
            - make build
            - make deploy
            - make docker
            - make javadoc
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0

  branches:
    "release/*":
      - step:
          size: 4x
          name: Build and Deploy - Release
          runs-on:
            - "linux"
            - "self.hosted"
          script:
            - make setup
            - make build
            - make deploy
            - make publish_github
            - make detach release
            - make COMMIT_MSG="Release:" commit tag
            - make push_tags publish_github_tags
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0

    "development/*":
      - step:
          size: 4x
          name: Build and Deploy - Development
          runs-on:
            - "linux"
            - "self.hosted"
          script:
            - make setup
            - make build
            - make deploy
            - make detach tag
            - make BRANCH=$BITBUCKET_BRANCH checkout
            - make patch
            - make COMMIT_MSG="[ci skip] Setting Next Version:" commit
            - make push push_tags publish_github publish_github_tags
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0

    "stealth/*":
      - step:
          size: 4x
          name: Build Only - Stealth
          runs-on:
            - "linux"
            - "self.hosted"
          script:
            - make setup
            - make build
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0

    main:
      - step:
          size: 4x
          name: Build and Deploy - Main
          services:
            - docker
          runs-on:
            - "linux"
            - "self.hosted"
          caches:
            - maven
          script:
            - make setup
            - make build
            - make deploy
            - make docker
            - make publish_github
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0

  default:
    - step:
        size: 4x
        name: Build and Deploy - Default
        services:
          - docker
        runs-on:
          - "linux"
          - "self.hosted"
        caches:
          - maven
        script:
          - make setup
          - make build
          - make deploy
          - make docker
          - make publish_github
        after-script:
          - pipe: atlassian/checkstyle-report:0.3.0