#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image:
  name: distribution.getelements.dev/elements-deployment-web-services-ci:c5869a4532309e906a99617730bd2adacbf3a955
  username: $REGISTRY_USER
  password: $REGISTRY_PASS

options:
  max-time: 30
  docker: true
  size: 2x

pipelines:
  default:
    - step:
        name: Security Scan
        script:
          # Run a security scan for sensitive data.
          # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
          - pipe: atlassian/git-secrets-scan:0.5.1
    - step:
        name: Git Submodule Checkout
        script:
          - git submodule update --init
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean test install
        after-script:
          # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
          - pipe: atlassian/checkstyle-report:0.3.0
