#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image:
  name: distribution.getelements.dev/elements-deployment-web-services-ci:c313ae099a36ed7adbe1203a2b9de2e700be3a10
  username: $REGISTRY_USER
  password: $REGISTRY_PASS

options:
  max-time: 60
  docker: true
  size: 2x

definitions:
  services:
    docker:
      image: docker:dind

pipelines:
  tags:
    "*":
      - step:
          size: 4x
          name: Build Tags
          runs-on:
            - "linux"
            - "self.hosted"
          script:
            - echo "Executing Release Build"
            - echo $REGISTRY_PASS | docker login --username $REGISTRY_USER --password-stdin distribution.getelements.dev
            - make git
            - make build
            - make docker
          after-script:
            # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
  branches:
    "release/*":
      - step:
          size: 4x
          name: Build and Test - Release
          runs-on:
            - "linux"
            - "self.hosted"
          script:
            - echo "Executing Release Build"
            - echo $REGISTRY_PASS | docker login --username $REGISTRY_USER --password-stdin distribution.getelements.dev
            - make git
            - make release
            - make COMMIT_MSG="Release" detach commit tag push_tags
          after-script:
            # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
    "development/*":
      - step:
          size: 4x
          name: Build and Test - Development
          runs-on:
            - "linux"
            - "self.hosted"
          script:
            - echo "Executing Branch Build"
            - echo $REGISTRY_PASS | docker login --username $REGISTRY_USER --password-stdin distribution.getelements.dev
            - make git
            - make patch
            - make COMMIT_MSG="[ci skip] Next Version" commit push
            - make COMMIT_MSG="Snapshot" detach commit tag push_tags
          after-script:
            # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
  default:
    - step:
        size: 4x
        name: Build and Test
        runs-on:
          - "linux"
          - "self.hosted"
        caches:
          - maven
        script:
          - echo "Running Default Build."
          - echo $REGISTRY_PASS | docker login --username $REGISTRY_USER --password-stdin distribution.getelements.dev
          - make build
          - make docker
        after-script:
          # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
          - pipe: atlassian/checkstyle-report:0.3.0
