#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image:
  name: distribution.getelements.dev/elements-deployment-web-services-ci:6abb67c5540a956b361ee7e7ad2a3ff40ae871fd
  username: $REGISTRY_USER
  password: $REGISTRY_PASS

options:
  max-time: 60
  docker: true
  size: 2x

pipelines:
  default:
    - step:
        size: 4x
        name: Build and Test
        runs-on:
          - "linux"
          - "self.hosted"
        caches:
          - maven
        script:
          - git submodule update --init --recursive
          - mvn -B clean test install
        after-script:
          # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
          - pipe: atlassian/checkstyle-report:0.3.0
