package com.namazustudios.socialengine.rt;

/**
 * A type used to receive the objects generated by requests.
 *
 * @param <HeaderT> the Header type
 */
public interface Receiver<HeaderT, PayloadT> {

    /**
     * After generating the desired type of header and payload,
     * the method will pass both types in to be delivered to the
     * client.
     *
     * @param header
     * @param payload
     */
    void receive(HeaderT header, PayloadT payload);

}
