package com.namazustudios.socialengine.rt;

/**
 * A type used to receive the data generated by a {@link Response}.
 *
 */
public interface ResponseReceiver {

    /**
     * After generating the desired type of header and payload, the method will
     * pass both types in to be delivered to the client.
     *
     * @param code the response code
     * @param payload the object payload for the response
     */
    void receive(int code, Object payload);

}
