/* tslint:disable */
import { Session } from './session';

/**
 * The mock session creation.
 */
export interface MockSessionCreation {

  /**
   * The Session Secret to pass to subsequent requests through headers.
   */
  sessionSecret?: string;

  /**
   * The Session object generated by the request.
   */
  session?: Session;

  /**
   * The assocaited mock user will automatically be deleted at supplied time.
   */
  userExpiresAt?: number;

  /**
   * The randomly-assigned password for the mock user.
   */
  password?: string;
}
