package com.namazustudios.socialengine.rt.edge;

/**
 * A type used to receive the objects generated by requests.
 */
public interface EdgeResponseReceiver {

    /**
     * After generating the desired type of header and payload,
     * the method will pass both types in to be delivered to the
     * client.
     *
     * @Param code
     * @param code
     * @param payload
     */
    void receive(int code, Object payload);

}
