package com.namazustudios.socialengine.model.auth;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;

@ApiModel(description = "Represents a response from creating an Auth Scheme for an Application.")
public class CreateAuthSchemeResponse {

    @ApiModelProperty("The full JSON response as described in AuthScheme")
    @NotNull
    public String scheme;

    @ApiModelProperty("The Base64 public key that was either given or generated during creation")
    @NotNull
    public String publicKey;

    @ApiModelProperty("The Base64 private key that was generated if the public key was generated by Elements")
    public String privateKey;
}
