package com.namazustudios.socialengine.model.auth;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;

@ApiModel(description = "Represents a response from updating an Auth Scheme for an Application.")
public class UpdateAuthSchemeResponse {

    @ApiModelProperty("The full JSON response as described in AuthScheme")
    public AuthScheme scheme;

    @ApiModelProperty("The Base64 public key that was either given or generated during creation")
    @NotNull
    public String publicKey;

    @ApiModelProperty("The Base64 private key that was generated if the public key was generated by Elements")
    public String privateKey;

    public AuthScheme getScheme() {
        return scheme;
    }

    public void setScheme(AuthScheme scheme) {
        this.scheme = scheme;
    }

    public String getPublicKey() { return publicKey; }

    public void setPublicKey(String publicKey) { this.publicKey = publicKey; }

    public String getPrivateKey() { return privateKey; }

    public void setPrivateKey(String privateKey) { this.privateKey = privateKey; }

}
