package com.namazustudios.socialengine.rt.git;

import com.namazustudios.socialengine.rt.ApplicationBootstrapper;
import com.namazustudios.socialengine.rt.Path;
import com.namazustudios.socialengine.rt.exception.InternalException;
import com.namazustudios.socialengine.rt.id.ApplicationId;
import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.inject.Inject;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Map;
import java.util.function.Function;
import java.util.function.Supplier;

public class GitApplicationBootstrapper implements ApplicationBootstrapper {

    private static final Logger logger = LoggerFactory.getLogger(GitApplicationBootstrapper.class);

    private static final String BOOTSTRAP_COMMIT_MESSAGE = "Automatically generated by application bootstrapper.";

    private GitLoader gitLoader;

    private Function<ApplicationId, BootstrapResources> applicationBootstrapperFunction;

    @Override
    public void bootstrap(final BootstrapUserMetadata bootstrapUserMetadata, final ApplicationId applicationId) {
        final BootstrapResources bootstrapResources = getApplicationBootstrapperFunction().apply(applicationId);
        getGitLoader().performInGit(applicationId, (g, f) -> doBootstrap(bootstrapUserMetadata, bootstrapResources, g, f));
    }

    private void doBootstrap(final BootstrapUserMetadata bootstrapUserMetadata,
                             final BootstrapResources bootstrapResources,
                             final Git git, final Function<Path, OutputStream> outputStreamSupplier) {
        checkMainBranch(git);
        createAndAddResources(bootstrapUserMetadata, bootstrapResources, git, outputStreamSupplier);
        commitBootstrap(bootstrapUserMetadata, git);
        pushBootstrap(git);
    }

    private void checkMainBranch(final Git git) {
        try {

            final String branch = git.getRepository().getBranch();

            if (GitLoader.DEFAULT_MAIN_BRANCH.equals(branch)) {
                logger.info("Using git branch {}", branch);
            } else {
                throw new InternalException("Invalid branch checked out: " + branch);
            }

        } catch (IOException ex) {
            throw new InternalException(ex);
        }
    }

    private void createAndAddResources(final BootstrapUserMetadata bootstrapUserMetadata,
                                       final BootstrapResources bootstrapResources,
                                       final Git git, final Function<Path, OutputStream> outputStreamSupplier) {
        final Map<Path, Supplier<InputStream>> pathSupplierMap = bootstrapResources.getBootstrapResources();
        pathSupplierMap.forEach((k,v) -> createAndAddResource(k, v, git, outputStreamSupplier));
    }

    private void createAndAddResource(
            final Path path, final Supplier<InputStream> inputStreamSupplier,
            final Git git, final Function<Path, OutputStream> outputStreamSupplier) {
        createResource(path, inputStreamSupplier, outputStreamSupplier);
        addResource(path, git);
    }

    private void createResource(final Path path,
                                final Supplier<InputStream> inputStreamSupplier,
                                final Function<Path, OutputStream> outputStreamSupplier) {
        try (final InputStream inputStream = inputStreamSupplier.get();
             final OutputStream outputStream = outputStreamSupplier.apply(path)) {
            logger.info("Copying {} to git directory.", path.toNormalizedPathString());
            inputStream.transferTo(outputStream);
            logger.info("Copied {} to git directory.", path.toNormalizedPathString());
        } catch (IOException ex) {
            throw new InternalException(ex);
        }
    }

    private void commitBootstrap(final BootstrapUserMetadata bootstrapUserMetadata, final Git git) {
        try {
            git.commit()
                .setMessage(BOOTSTRAP_COMMIT_MESSAGE)
                .setCommitter(bootstrapUserMetadata.getName(), bootstrapUserMetadata.getEmail())
                .call();
        } catch (GitAPIException ex) {
            throw new InternalException(ex);
        }
    }

    private void pushBootstrap(final Git git) {
        try {
            git.push().call();
        } catch (GitAPIException ex) {
            throw new InternalException(ex);
        }
    }

    private void addResource(final Path path, final Git git) {
        try {
            logger.info("Adding {}", path.toNormalizedPathString());
            git.add().addFilepattern(path.toNormalizedPathString()).call();
            logger.info("Added {}", path.toNormalizedPathString());
        } catch (GitAPIException ex) {
            throw new InternalException(ex);
        }
    }

    public GitLoader getGitLoader() {
        return gitLoader;
    }

    @Inject
    public void setGitLoader(GitLoader gitLoader) {
        this.gitLoader = gitLoader;
    }

    public Function<ApplicationId, BootstrapResources> getApplicationBootstrapperFunction() {
        return applicationBootstrapperFunction;
    }

    @Inject
    public void setApplicationBootstrapperFunction(Function<ApplicationId, BootstrapResources> applicationBootstrapperFunction) {
        this.applicationBootstrapperFunction = applicationBootstrapperFunction;
    }

}
