package dev.getelements.elements.model.session;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel
public class AppleSignInSessionCreation {

    @ApiModelProperty("The Session object generated by the request.")
    private Session session;

    @ApiModelProperty("The Session Secret to pass to subsequent requests through headers.")
    private String sessionSecret;

    @ApiModelProperty("The OAuth user access token obtained via the Apple Sign-In API.")
    private String userAccessToken;

    public String getSessionSecret() {
        return sessionSecret;
    }

    public void setSessionSecret(String sessionSecret) {
        this.sessionSecret = sessionSecret;
    }

    public Session getSession() {
        return session;
    }

    public void setSession(Session session) {
        this.session = session;
    }

    public String getUserAccessToken() {
        return userAccessToken;
    }

    public void setUserAccessToken(String userAccessToken) {
        this.userAccessToken = userAccessToken;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AppleSignInSessionCreation that = (AppleSignInSessionCreation) o;
        return Objects.equals(getSessionSecret(), that.getSessionSecret()) &&
                Objects.equals(getSession(), that.getSession()) &&
                Objects.equals(getUserAccessToken(), that.getUserAccessToken());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSessionSecret(), getSession(), getUserAccessToken());
    }

    @Override
    public String toString() {
        return "AppleSignInSessionCreation{" +
                "session=" + session +
                '}';
    }

}
