package dev.getelements.elements.model.session;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel
public class GoogleSignInSessionCreation {

    @ApiModelProperty("The Session object generated by the request.")
    private Session session;

    @ApiModelProperty("The Session Secret to pass to subsequent requests through headers.")
    private String sessionSecret;

    public String getSessionSecret() {
        return sessionSecret;
    }

    public void setSessionSecret(String sessionSecret) {
        this.sessionSecret = sessionSecret;
    }

    public Session getSession() {
        return session;
    }

    public void setSession(Session session) {
        this.session = session;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GoogleSignInSessionCreation that = (GoogleSignInSessionCreation) o;
        return Objects.equals(getSessionSecret(), that.getSessionSecret()) &&
                Objects.equals(getSession(), that.getSession());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSessionSecret(), getSession());
    }

    @Override
    public String toString() {
        return "GoogleSignInSessionCreation{" +
                "session=" + session +
                '}';
    }

}
