package dev.getelements.elements.model.session;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel
public class SessionCreation {

    @ApiModelProperty("The Session Secret to pass to subsequent requests through headers.")
    private String sessionSecret;

    @ApiModelProperty("The Session object generated by the request.")
    private Session session;

    public String getSessionSecret() {
        return sessionSecret;
    }

    public void setSessionSecret(String sessionSecret) {
        this.sessionSecret = sessionSecret;
    }

    public Session getSession() {
        return session;
    }

    public void setSession(Session session) {
        this.session = session;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SessionCreation)) return false;

        SessionCreation that = (SessionCreation) o;

        if (getSessionSecret() != null ? !getSessionSecret().equals(that.getSessionSecret()) : that.getSessionSecret() != null)
            return false;
        return getSession() != null ? getSession().equals(that.getSession()) : that.getSession() == null;
    }

    @Override
    public int hashCode() {
        int result = getSessionSecret() != null ? getSessionSecret().hashCode() : 0;
        result = 31 * result + (getSession() != null ? getSession().hashCode() : 0);
        return result;
    }

}
