/* tslint:disable */
import { Session } from './session';

/**
 * Represents a response from the Facebook authentication service.
 */
export interface FacebookSessionCreation {

  /**
   * The Session Secret to pass to subsequent requests through headers.
   */
  sessionSecret?: string;

  /**
   * The Session object generated by the request.
   */
  session?: Session;

  /**
   * The Facebook user access token obtained via the Facebook API.
   */
  userAccessToken?: string;
}
