package dev.getelements.elements.sdk.test;

import dev.getelements.elements.sdk.ElementPathLoader;

import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.util.Map;
import java.util.Properties;

import static dev.getelements.elements.sdk.ElementPathLoader.LIB_DIR;
import static dev.getelements.elements.sdk.ElementPathLoader.SPI_DIR;
import static java.nio.file.Files.createDirectories;

public class TestUtils {
    public static void layoutSkeletonElement(final Path parent, final Map<?, ?> attributes) throws IOException {

        createDirectories(parent);
        createDirectories(parent.resolve(SPI_DIR));
        createDirectories(parent.resolve(LIB_DIR));
        createDirectories(parent.resolve(ElementPathLoader.CLASSPATH_DIR));

        final var attributesPropertiesFile = parent.resolve(ElementPathLoader.ATTRIBUTES_PROPERTIES_FILE).toFile();

        try (final var fos = new FileOutputStream(attributesPropertiesFile)) {
            final var attributesProperties = new Properties();
            attributesProperties.putAll(attributes);
            attributesProperties.store(fos, "Generated by integration tests.");
        }

    }
}
