
# A docker-compose file which incorporates all necessary services that SocialEngine needs
# to run in development mode.  This does not include and security and exposes all ports
# the outside world such that the user may connected to the various underlying services.
#
# This could be used as a base for a production deployment, but deploying as-is is not
# recommended for the above reasons.

version: '3'
services:

  redis:
    image: redis:4.0.1
    deploy:
      replicas: 1
    networks:
      - socialengine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:3.4.6
    deploy:
      replicas: 1
    networks:
      - socialengine
    ports:
      - "27017:27017"

  setup:
    build:
      context: ./setup
    depends_on:
      - mongo
    links:
      - mongo
    deploy:
      replicas: 1

#  api:
#    build:
#      context: ./api
#    depends_on:
#      - mongo
#      - redis
#    deploy:
#      replicas: 1
#    links:
#      - redis
#      - mongo
#    networks:
#      - socialengine
#    ports:
#      - "8081:8080"
#
#  ui:
#    build:
#      context: ./ui
#    depends_on:
#      - api
#    deploy:
#      replicas: 1
#    networks:
#      - socialengine
#    ports:
#      - "8080:8080"

networks:
  socialengine:
