
# A docker-compose file which incorporates all necessary services that elements needs
# to run in development mode.  This does not include and security and exposes all ports
# the outside world such that the user may connected to the various underlying services.
#
# This could be used as a base for a production deployment, but deploying as-is is not
# recommended for the above reasons.

version: '3'
services:

  discovery:
    build:
      context: ./discovery
    networks:
      - elements

  redis:
    image: redis:4.0.1
    networks:
      - elements
    ports:
      - "6379:6379"

  mongo:
    image: mongo:3.4.6
    networks:
      - elements
    ports:
      - "27017:27017"

  setup:
    build:
      context: ./setup
    networks:
      - elements
    depends_on:
      - mongo
    links:
      - mongo

  ui:
    build:
      context: ./ui
    depends_on:
      - api
    networks:
      - elements
    ports:
      - "8080:8080"

  api:
    build:
      context: ./api
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    networks:
      - elements
    ports:
      - "8081:8081"
    volumes:
      - script-repos:/opt/elements/script-repos

  code-serve:
    build:
      context: ./code-serve
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    networks:
      - elements
    ports:
      - "8082:8082"
    volumes:
      - script-repos:/opt/elements/script-repos

  cdn-serve:
    build:
      context: ./cdn-serve
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    deploy:
      replicas: 1
    networks:
      - socialengine
    ports:
      - "8084:8084"
    volumes:
      - cdn-repos:/opt/socialengine/cdn-repos

  app-serve:
    build:
      context: ./app-serve
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    networks:
      - elements
    ports:
      - "8083:8083"
    volumes:
      - script-repos:/opt/elements/script-repos

  app-node-0:
    build:
      context: ./app-node
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    networks:
      - elements
    ports:
      - "28883:28883"
    volumes:
      - script-repos:/opt/elements/script-repos

  app-node-1:
    build:
      context: ./app-node
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    networks:
      - elements
    ports:
      - "28884:28883"
    volumes:
      - script-repos:/opt/elements/script-repos

networks:
  elements:

volumes:
  script-repos:
  cdn-repos:
