
# A docker-compose file which incorporates all necessary services that SocialEngine needs
# to run in development mode.  This does not include and security and exposes all ports
# the outside world such that the user may connected to the various underlying services.
#
# This could be used as a base for a production deployment, but deploying as-is is not
# recommended for the above reasons.

version: '3'
services:

  discovery:
    image: andyshinn/dnsmasq:2.76
    command:
      - -d
      - -W
      - _elements._tcp.internal,app-node-0,28883,1
      - -W
      - _elements._tcp.internal,app-node-1,28884,1
      - -W
      - _mongodb._tcp.internal,mongo,27017
    ports:
      - 53/udp

  redis:
    image: redis:4.0.1
    networks:
      - socialengine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:3.4.6
    networks:
      - socialengine
    ports:
      - "27017:27017"

  setup:
    build:
      context: ./setup
    networks:
      - socialengine
    depends_on:
      - mongo
    links:
      - mongo

  ui:
    build:
      context: ./ui
    depends_on:
      - api
    networks:
      - socialengine
    ports:
      - "8080:8080"

  api:
    build:
      context: ./api
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    networks:
      - socialengine
    ports:
      - "8081:8081"
    volumes:
      - script-repos:/opt/socialengine/script-repos

  code-serve:
    build:
      context: ./code-serve
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    networks:
      - socialengine
    ports:
      - "8082:8082"
    volumes:
      - script-repos:/opt/socialengine/script-repos

  app-serve:
    build:
      context: ./app-serve
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    networks:
      - socialengine
    ports:
      - "8083:8083"
    volumes:
      - script-repos:/opt/socialengine/script-repos

  app-node-0:
    build:
      context: ./app-node
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    networks:
      - socialengine
    ports:
      - "28883:28883"
    volumes:
      - script-repos:/opt/socialengine/script-repos

  app-node-1:
    build:
      context: ./app-node
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    networks:
      - socialengine
    ports:
      - "28884:28883"
    volumes:
      - script-repos:/opt/socialengine/script-repos

networks:
  socialengine:

volumes:
  script-repos:
