//package com.namazustudios.socialengine.rt;
//
//import java.util.function.Consumer;
//
///**
// * A type used to dispatch the data generated by a {@link Response}.
// */
//public interface ResponseReceiver<ResponseT extends Response> extends Consumer<ResponseT> {
//
//    /**
//     * Used to dispatch an instance of {@link Response}.
//     */
//    @Deprecated
//    default void receive(ResponseT response) {
//        accept(response);
//    }
//
//}
