package com.namazustudios.socialengine.rt;

/**
 * A type used to receive the data generated by a {@link Response}.
 */
public interface ResponseReceiver {

    /**
     * Used to receive an instance of {@link Response}.
     */
    void receive(Response response);

}
