package dev.getelements.elements.model;

import io.swagger.annotations.ApiModel;

import javax.validation.constraints.NotNull;
import java.io.Serializable;

/**
 * Represents a short link.  The short links are generated by the system and
 * can be tracked in some way.
 *
 * Created by patricktwohig on 6/9/15.
 */
@ApiModel
public class ShortLink implements Serializable {

    private String id;

    private String shortLinkPath;

    private String shortLinkURL;

    @NotNull
    private String destinationURL;

    /**
     * Gets the path of the short link.  This is the path relative to
     * the short link url base.
     *
     * @return the short link path
     *
     */
    public String getShortLinkPath() {
        return shortLinkPath;
    }

    public void setShortLinkPath(String shortLinkPath) {
        this.shortLinkPath = shortLinkPath;
    }

    /**
     * Gets the ID of the link.
     *
     * @return the ID
     */
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the short link URL, this is the URL which can be shared
     * with the user.
     *
     * @return the short link URL
     */
    public String getShortLinkURL() {
        return shortLinkURL;
    }

    public void setShortLinkURL(String shortLinkURL) {
        this.shortLinkURL = shortLinkURL;
    }

    /**
     * Gets the destination, or target url.  This is the url to which
     * the short link URL redirects.
     *
     * @return the destination URL
     */
    public String getDestinationURL() {
        return destinationURL;
    }

    public void setDestinationURL(String destinationURL) {
        this.destinationURL = destinationURL;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ShortLink)) return false;

    ShortLink shortLink = (ShortLink) o;

        if (getId() != null ? !getId().equals(shortLink.getId()) : shortLink.getId() != null) return false;
        if (getShortLinkPath() != null ? !getShortLinkPath().equals(shortLink.getShortLinkPath()) : shortLink.getShortLinkPath() != null)
            return false;
        if (getShortLinkURL() != null ? !getShortLinkURL().equals(shortLink.getShortLinkURL()) : shortLink.getShortLinkURL() != null)
            return false;
        return getDestinationURL() != null ? getDestinationURL().equals(shortLink.getDestinationURL()) : shortLink.getDestinationURL() == null;
}

    @Override
    public int hashCode() {
        int result = getId() != null ? getId().hashCode() : 0;
        result = 31 * result + (getShortLinkPath() != null ? getShortLinkPath().hashCode() : 0);
        result = 31 * result + (getShortLinkURL() != null ? getShortLinkURL().hashCode() : 0);
        result = 31 * result + (getDestinationURL() != null ? getDestinationURL().hashCode() : 0);
        return result;
    }

}

