package com.namazustudios.socialengine.rt;

/**
 * The main interface for the {@link Client}.
 *
 * Created by patricktwohig on 9/3/15.
 */
public interface Client {

    void sendRequest(Request request, Receiver receiver);

    /**
     * A simple interfae that allows the user of this interface to receive instances of
     * {@link Response} generated by a {@link Request}.
     */
    interface Receiver {

        void receive(Response receiver);

    }

}
