package dev.getelements.elements.sdk.model.blockchain.contract.near;



import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

/** Represents the outcome of a NEAR protocol transaction or receipt execution. */
public class NearOutcome {

    /** Creates a new instance. */
    public NearOutcome() {}

    @Schema(description = "logs")
    private List<String> logs;
    @Schema(description = "receipt_ids")
    private List<String> receiptIds;
    @Schema(description = "gas_burnt")
    private long gasBurnt;
    @Schema(description = "tokens_burnt")
    private String tokensBurnt;
    @Schema(description = "executor_id")
    private String executorId;
    @Schema(description = "status")
    private NearStatus status;
    @Schema(description = "metadata")
    private NearMetadata metadata;

    /**
     * Returns the log messages produced during execution.
     *
     * @return the logs
     */
    public List<String> getLogs() {
        return logs;
    }

    /**
     * Sets the log messages produced during execution.
     *
     * @param logs the logs
     */
    public void setLogs(List<String> logs) {
        this.logs = logs;
    }

    /**
     * Returns the IDs of receipts generated by this execution.
     *
     * @return the receipt IDs
     */
    public List<String> getReceiptIds() {
        return receiptIds;
    }

    /**
     * Sets the IDs of receipts generated by this execution.
     *
     * @param receiptIds the receipt IDs
     */
    public void setReceiptIds(List<String> receiptIds) {
        this.receiptIds = receiptIds;
    }

    /**
     * Returns the amount of gas burned during execution.
     *
     * @return the gas burnt
     */
    public long getGasBurnt() {
        return gasBurnt;
    }

    /**
     * Sets the amount of gas burned during execution.
     *
     * @param gasBurnt the gas burnt
     */
    public void setGasBurnt(long gasBurnt) {
        this.gasBurnt = gasBurnt;
    }

    /**
     * Returns the amount of tokens burned during execution.
     *
     * @return the tokens burnt
     */
    public String getTokensBurnt() {
        return tokensBurnt;
    }

    /**
     * Sets the amount of tokens burned during execution.
     *
     * @param tokensBurnt the tokens burnt
     */
    public void setTokensBurnt(String tokensBurnt) {
        this.tokensBurnt = tokensBurnt;
    }

    /**
     * Returns the account ID of the executor.
     *
     * @return the executor ID
     */
    public String getExecutorId() {
        return executorId;
    }

    /**
     * Sets the account ID of the executor.
     *
     * @param executorId the executor ID
     */
    public void setExecutorId(String executorId) {
        this.executorId = executorId;
    }

    /**
     * Returns the execution status.
     *
     * @return the status
     */
    public NearStatus getStatus() {
        return status;
    }

    /**
     * Sets the execution status.
     *
     * @param status the status
     */
    public void setStatus(NearStatus status) {
        this.status = status;
    }

    /**
     * Returns the execution metadata.
     *
     * @return the metadata
     */
    public NearMetadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the execution metadata.
     *
     * @param metadata the metadata
     */
    public void setMetadata(NearMetadata metadata) {
        this.metadata = metadata;
    }
}
