package dev.getelements.elements.sdk.model.session;

import io.swagger.v3.oas.annotations.media.Schema;


/** Represents the result of a session creation request, containing the session secret and session details. */
@Schema
public class SessionCreation {

    /** Creates a new instance. */
    public SessionCreation() {}

    @Schema(description = "The Session Secret to pass to subsequent requests through headers.")
    private String sessionSecret;

    @Schema(description = "The Session object generated by the request.")
    private Session session;

    /**
     * Returns the session secret to be passed to subsequent requests through headers.
     *
     * @return the session secret
     */
    public String getSessionSecret() {
        return sessionSecret;
    }

    /**
     * Sets the session secret to be passed to subsequent requests through headers.
     *
     * @param sessionSecret the session secret
     */
    public void setSessionSecret(String sessionSecret) {
        this.sessionSecret = sessionSecret;
    }

    /**
     * Returns the session object generated by the request.
     *
     * @return the session
     */
    public Session getSession() {
        return session;
    }

    /**
     * Sets the session object generated by the request.
     *
     * @param session the session
     */
    public void setSession(Session session) {
        this.session = session;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SessionCreation)) return false;

        SessionCreation that = (SessionCreation) o;

        if (getSessionSecret() != null ? !getSessionSecret().equals(that.getSessionSecret()) : that.getSessionSecret() != null)
            return false;
        return getSession() != null ? getSession().equals(that.getSession()) : that.getSession() == null;
    }

    @Override
    public int hashCode() {
        int result = getSessionSecret() != null ? getSessionSecret().hashCode() : 0;
        result = 31 * result + (getSession() != null ? getSession().hashCode() : 0);
        return result;
    }

}
