package dev.getelements.elements.rt.remote;

import dev.getelements.elements.sdk.cluster.id.DeploymentId;
import dev.getelements.elements.rt.remote.InstanceConnectionService.InstanceBinding;

import java.util.Collection;
import java.util.Set;

/**
 * Represents the worker, hosing one or more nodes performing work.
 */
public interface Worker {

    /**
     * Opens a {@link Mutator} which can be used to modify the run-state of this {@link Worker}.
     *
     * @return the {@link Mutator}
     */
    Mutator beginMutation();

    /**
     * Opens an {@link Accessor} which can be used to read the run-state of this {@link Worker}.
     *
     * @return the {@link Accessor}
     */
    Accessor accessWorkerState();

    /**
     * Allows client code to read the sstate of the {@link Worker}
     */
    interface Accessor extends AutoCloseable {

        /**
         * Gets all {@link Node} instances running in this {@link Worker}.
         *
         * @return a {@link Set<Node>}
         */
        Set<Node> getNodeSet();

        /**
         * Gets all active {@link InstanceBinding}s.
         *
         * @return the binding set
         */
        Set<InstanceBinding> getBindingSet();

        /**
         * Releases any resources associated with the {@link Mutator}.
         */
        void close();

    }

    /**
     * Allows for the mutation of the {@link Worker}.
     */
    interface Mutator extends Accessor, AutoCloseable {

        /**
         * Adds a new node with the supplied {@link DeploymentId}.
         *
         * @param deploymentId the {@link DeploymentId} to add
         * @return this instance
         */
        Mutator addNode(DeploymentId deploymentId);

        /**
         * Adds a new node with the supplied application unique name. The {@link DeploymentId} is generated by using
         * {@link DeploymentId#forUniqueName(String)}
         *
         * @param deploymentUniqueName the application unique name
         * @return this instance
         */
        default Mutator addNode(final String deploymentUniqueName) {
            final var deploymentId = DeploymentId.forUniqueName(deploymentUniqueName);
            return addNode(deploymentId);
        }

        /**
         * Restarts the supplied {@link Node} with the supplied {@link DeploymentId}.
         * @param deploymentId the {@link DeploymentId} to restart
         * @return this instance
         */
        Mutator restartNode(DeploymentId deploymentId);

        /**
         * Restarts the supplied {@link Node}s with the supplied {@link DeploymentId}s.
         * @param toRestart a {@link Collection<DeploymentId>} to restart in succession
         * @return this instance
         **/
        default Mutator restartNode(final Collection<DeploymentId> toRestart) {
            toRestart.forEach(this::restartNode);
            return this;
        }

        /**
         * Restarts the supplied {@link Node} with the supplied name. The {@link DeploymentId} is generated by using
         * {@link DeploymentId#forUniqueName(String)}.
         *
         * @param deploymentUniqueName the application unique name
         * @return this instance
         */
        default Mutator restartNode(final String deploymentUniqueName) {
            final var deploymentId = DeploymentId.forUniqueName(deploymentUniqueName);
            return restartNode(deploymentId);
        }

        /**
         * Removes the supplied {@link Node} with the supplied {@link DeploymentId}.
         * @param deploymentId the {@link DeploymentId} to restart
         * @return this instance
         */
        Mutator removeNode(DeploymentId deploymentId);

        /**
         * Removes the supplied {@link Node}s with the supplied {@link DeploymentId}s.
         * @param toRestart a {@link Collection<DeploymentId>} to restart in succession
         * @return this instance
         **/
        default Mutator removeNode(final Collection<DeploymentId> toRestart) {
            toRestart.forEach(this::removeNode);
            return this;
        }

        /**
         * Removes the supplied {@link Node} with the supplied name. The {@link DeploymentId} is generated by using
         * {@link DeploymentId#forUniqueName(String)}.
         *
         * @param deploymentUniqueName the application unique name
         * @return this instance
         */
        default Mutator removeNode(final String deploymentUniqueName) {
            final var deploymentId = DeploymentId.forUniqueName(deploymentUniqueName);
            return removeNode(deploymentId);
        }

        /**
         * Commits any changes to the {@link Worker}.
         * @return this instance
         */
        Mutator commit();

    }

}
